//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuHaftakiFilmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuHaftakiFilmler()
        {
            this.BuHaftaFilmYorumlari = new HashSet<BuHaftaFilmYorumlari>();
            this.BuHaftakiFilmKullaniciNotu = new HashSet<BuHaftakiFilmKullaniciNotu>();
        }
    
        public int filmid { get; set; }
        public string filmadi { get; set; }
        public string filmresim { get; set; }
        public string filmicerik { get; set; }
        public Nullable<int> genel_not { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuHaftaFilmYorumlari> BuHaftaFilmYorumlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuHaftakiFilmKullaniciNotu> BuHaftakiFilmKullaniciNotu { get; set; }
    }
}
