//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmProjesiDatabaseEntities : DbContext
    {
        public FilmProjesiDatabaseEntities()
            : base("name=FilmProjesiDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuHaftaFilmYorumlari> BuHaftaFilmYorumlari { get; set; }
        public virtual DbSet<BuHaftakiFilmKullaniciNotu> BuHaftakiFilmKullaniciNotu { get; set; }
        public virtual DbSet<BuHaftakiFilmler> BuHaftakiFilmler { get; set; }
        public virtual DbSet<GelecekHaftakiFilmler> GelecekHaftakiFilmler { get; set; }
        public virtual DbSet<Haberler> Haberler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<ListeliFilmKategori> ListeliFilmKategori { get; set; }
        public virtual DbSet<ListeliFilmler> ListeliFilmler { get; set; }
        public virtual DbSet<ListeliFilmOyuncu> ListeliFilmOyuncu { get; set; }
        public virtual DbSet<ListeliFilmYorumları> ListeliFilmYorumları { get; set; }
        public virtual DbSet<Oyuncular> Oyuncular { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<SliderIcerik> SliderIcerik { get; set; }
        public virtual DbSet<FilmElestirileri> FilmElestirileri { get; set; }
    }
}
