//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelecekHaftakiFilmler
    {
        public int filmid { get; set; }
        public string filmadi { get; set; }
        public string filmresim { get; set; }
        public string filmicerik { get; set; }
    }
}
