//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int haberid { get; set; }
        public string haberadi { get; set; }
        public string haberresim { get; set; }
        public string habericerik { get; set; }
        public Nullable<bool> habermanset { get; set; }
    }
}
