//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.BuHaftakiFilmKullaniciNotu = new HashSet<BuHaftakiFilmKullaniciNotu>();
            this.Yorumlar = new HashSet<Yorumlar>();
            this.FilmElestirileri = new HashSet<FilmElestirileri>();
        }
    
        public int kullaniciid { get; set; }
        public string kullaniciadi { get; set; }
        public string kullanicisifre { get; set; }
        public string kullaniciemail { get; set; }
        public string kullaniciyetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuHaftakiFilmKullaniciNotu> BuHaftakiFilmKullaniciNotu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmElestirileri> FilmElestirileri { get; set; }
    }
}
