//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeliFilmKategori
    {
        public int id { get; set; }
        public int filmid { get; set; }
        public int kategoriid { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual ListeliFilmler ListeliFilmler { get; set; }
    }
}
