//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oyuncular()
        {
            this.ListeliFilmOyuncu = new HashSet<ListeliFilmOyuncu>();
        }
    
        public int oyuncuid { get; set; }
        public string oyuncuadi { get; set; }
        public string oyuncubiyografi { get; set; }
        public string oyuncudogumtarihi { get; set; }
        public string oyuncuresim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListeliFilmOyuncu> ListeliFilmOyuncu { get; set; }
    }
}
