//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderIcerik
    {
        public int slidericerikid { get; set; }
        public string slidericerikbaslik { get; set; }
        public string slidericerikresim { get; set; }
        public string slidericerik1 { get; set; }
        public Nullable<int> sliderid { get; set; }
    
        public virtual Slider Slider { get; set; }
    }
}
