//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmArsivProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorumlar()
        {
            this.BuHaftaFilmYorumlari = new HashSet<BuHaftaFilmYorumlari>();
            this.ListeliFilmYorumları = new HashSet<ListeliFilmYorumları>();
        }
    
        public int yorumid { get; set; }
        public string yorum { get; set; }
        public string yorumsaati { get; set; }
        public string yorumtarihi { get; set; }
        public Nullable<int> kullaniciid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuHaftaFilmYorumlari> BuHaftaFilmYorumlari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListeliFilmYorumları> ListeliFilmYorumları { get; set; }
    }
}
